"""DTOs for the patient state snapshot."""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class PatientStateSnapshot(BaseModel):
    """
    Structured snapshot stored in patient_state.snapshot (JSONB).

    Regenerated by ConsolidationService whenever facts change. Designed to be
    rendered directly into a prompt as "Active Clinical Facts".
    """

    model_config = ConfigDict(from_attributes=True)

    patient_id: uuid.UUID
    version: int
    last_consolidated_at: datetime

    summary_text: str | None = None
    risk_level: str = "none"

    # Structured per fact_type; each entry is the active fact's projection.
    allergies: list[dict[str, Any]] = Field(default_factory=list)
    medications: list[dict[str, Any]] = Field(default_factory=list)
    symptoms: list[dict[str, Any]] = Field(default_factory=list)
    conditions: list[dict[str, Any]] = Field(default_factory=list)
    chronic_conditions: list[dict[str, Any]] = Field(default_factory=list)
    unresolved_followups: list[dict[str, Any]] = Field(default_factory=list)
    recent_lab_values: list[dict[str, Any]] = Field(default_factory=list)
    lifestyle: list[dict[str, Any]] = Field(default_factory=list)
    preferences: list[dict[str, Any]] = Field(default_factory=list)

    def is_empty(self) -> bool:
        return not any(
            [
                self.allergies,
                self.medications,
                self.symptoms,
                self.conditions,
                self.chronic_conditions,
                self.unresolved_followups,
            ]
        )
